GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/afc44bd5-c436-4e35-8b89-9481e7182969

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Movie"
}

###
PUT http://localhost:3000/categories/afc44bd5-c436-4e35-8b89-9481e7182969
Content-Type: application/json

{
    "name": "Movie111111"
}

###
DELETE  http://localhost:3000/categories/d71a0d03-39e7-424e-b96b-b3e235570b97
Content-Type: application/json