GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/5189436b-0fd3-401b-8977-454c45d5abba

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Movie"
}

###
PUT http://localhost:3000/categories/a011d145-b3ad-46da-a895-64991376859c
Content-Type: application/json

{
    "name": "Movie111111"
}

###
DELETE  http://localhost:3000/categories/d71a0d03-39e7-424e-b96b-b3e235570b97
Content-Type: application/json